### ISSUE TITLE
Atom crashing when open terminal.

### ISSUE THREAD

**Issue by theol0403** [purduesigbots/pros-atom3#26]
When I click on New Terminal (CTRL+SHIFT+T), a window appears for a brief period of time then Atom crashes. Going into the terminal-tab-plus package settings and changing the shell to "cmd" and "powershell" does nothing.

Right before it crashes, there is sometimes a brief flash of text something along the lines of "to learn more..."

The behavior does not seem to change if I disable the terminal-tab-plus package, so the issue is probably within the tool-bar or the PROS package.

I have dodged the issue by installing platformio-ide-terminal.

![image](https://user-images.githubusercontent.com/16546293/45052366-75294c80-b03b-11e8-8629-685332ee7c23.png)

![image](https://user-images.githubusercontent.com/16546293/45052150-d43a9180-b03a-11e8-9d67-97bd9e7e6b18.png)

![image](https://user-images.githubusercontent.com/16546293/45052160-dbfa3600-b03a-11e8-8d6f-8d83e5381259.png)

Desktop
 - OS: Windows
 - Version 3.1.0

**Comment by HotelCalifornia** [comment]
pretty sure this is an issue with the terminal plugin

**Comment by edjubuh** [comment]
What version of terminal-tab-plus do you have installed?

**Comment by theol0403** [comment]
Look at the first screenshot.
0.5.10
It is currently disabled, though that does not affect the issue.
The issue is located I think somewhere between the button press and the terminal.
I don't think it can be an issue with the terminal plugin, since it is disabled, but rather the "Terminal" window or the PROS toolbar.

**Comment by theol0403** [comment]
Upgraded pros plugin to 1.0.3
Still crashes

**Comment by HotelCalifornia** [comment]
@theol0403 can you try opening the terminal after opening a pros project file (like opcontrol.cpp)?

**Comment by theol0403** [comment]
?????
Today, for some reason, the tool-bar disappeared.
I re-toggled it, and now the problem is gone!
The terminal works fine now.
I am unable to reproduce the problem.
I will update if it happens again.
Thanks for the support.
