### ISSUE TITLE
Allow copying text from the terminal window

### ISSUE THREAD

**Issue by graham615** [purduesigbots/pros-atom3#33]
#### Expected Behavior:
Using printf statements to output telemetry to the terminal window I had hoped the data could be copied to the clipboard using cut/copy/paste.

#### Actual Behavior:
When the text was selected in the window and copied, when pasted in another window, no test appeared.

#### Steps to reproduce:
printf output to the terminal
select the text in the terminal pane
select Edit->copy
in a unrelated application ( notepad), Excel, select paste
no text is pasted

#### System information:
Platform: V5
PROS Kernel Version:1.34

**Comment by HotelCalifornia** [comment]
I'm going to close this issue as resolved for now. @graham615 please feel free to reopen this issue if it wasn't resolved to your satisfaction
