### ISSUE TITLE
Project Upgrade: cmd.exe could not be spawned

### ISSUE THREAD

**Issue by graham615** [purduesigbots/pros-atom3#34]
#### Expected Behavior:
Pros and okapi upgraded to the latest versions

#### Actual Behavior:
Red Error Box containing:
'C:\WINDOWS\system32\cmd.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

#### Steps to reproduce:
PROS->Upgrade Project
Point to top level project directory
Select upgrade to latest
Verified path and existence of cmd.exe.  Opened pros in Admin.

#### System information:
Platform: 
PROS Kernel Version: V% 3.1.5

#### Additional Information
kage spawning the process.
![image](https://user-images.githubusercontent.com/47017006/52811182-1b9d6300-305a-11e9-999d-bff765a9ffe6.png)

**Comment by HotelCalifornia** [comment]
@graham615 is it possible the project path had spaces in it?

**Comment by graham615** [comment]
Our path is: C:\Users\ghenderson\Documents\2018\App
As a work around, we simply removed all the project files except for the source and opened a new project.  Unfortunately, our season is over as of Saturday.  We will be looking forward to future pros developments.
    On Monday, February 25, 2019, 10:38:01 AM CST, Alex Brooke <notifications@github.com> wrote:  
 
 
@graham615 is it possible the project path had spaces in it?
