### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by WillC20** [purduesigbots/pros-atom3#37]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.3
**Thrown From**: [pros-atom3](https://github.com/purduesigbots/pros-atom3) package 1.1.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/PROS%20Editor.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /packages/pros-atom3/node_modules/@purduesigbots/pros-cli-middleware/dist/util.js:110:38)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
  5x -1:32.6.0 core:backspace (input.hidden-input)
     -1:22.5.0 core:save (input.hidden-input)
     -1:21.5.0 pros:quick-action (input.hidden-input)
     -1:21.5.0 pros:terminal (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -1:21.4.0 pros:build (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -1:18 pros:upload (atom-text-editor.editor.enable-atom-ide-find-references)
     -0:54.6.0 pros:quick-action (textarea.xterm-helper-textarea)
     -0:54.6.0 pros:terminal (atom-text-editor.editor.enable-atom-ide-find-references)
     -0:54.5.0 pros:build (atom-text-editor.editor.enable-atom-ide-find-references)
     -0:53.4.0 pros:upload (atom-text-editor.editor.enable-atom-ide-find-references)
  4x -0:20.3.0 core:backspace (input.hidden-input)
     -0:17.5.0 core:save (input.hidden-input)
     -0:16 pros:quick-action (input.hidden-input)
     -0:16 pros:terminal (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -0:16 pros:build (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -0:13.7.0 pros:upload (atom-text-editor.editor.enable-atom-ide-find-references)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
busy 0.7.0 
busy-signal 2.0.0 
file-icons 2.1.30 
ide-cquery 0.14.0 
minimap 4.29.9 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-selection 4.5.0 
pros-atom3 1.1.0 
teletype 0.13.3 
terminal-tab-plus 0.5.11 
tool-bar 1.1.11 
tool-bar-main 0.0.11 
touchbar 0.14.2 
touchbar-utility 3.3.0 
```

**Comment by edjubuh** [comment]
I'm not sure why we're getting this error. If you're willing to debug, it would be much appreciated if you could pop a breakpoint on the culprit line (inside @purduesigbots/pros-cli-middleware/dist/util.js:110) to see what the data looks like. If not, we'll add a try/catch to at least print out the line to the console (but that won't really solve the issue)

**Comment by DeHota** [comment]
I am getting this same error. 
![image](https://user-images.githubusercontent.com/49534306/55983804-f304a480-5c69-11e9-8a3a-8430a9e4e830.png).

Any help solving this would be appreciated.

**Comment by barcbots** [comment]
I am getting the same error with a new installation of PROS on my system. I am not sure how to proceed

**Comment by edjubuh** [comment]
I'm not sure why we're getting this error. If you're willing to debug, it would be much appreciated if you could pop a breakpoint on the culprit line (inside @purduesigbots/pros-cli-middleware/dist/util.js:110) to see what the data looks like. If you'd like help walking through this, join [our Slack](https://pros-development.slack.com) and we'll be glad to take you through the steps.

**Comment by mvas8037** [comment]
I'm getting the same issue, I don't know why. It would be extremely helpful if you could update me on the issue, as in, has there been any solve to it? I'm on macOS btw.

**Comment by HotelCalifornia** [comment]
>I'm not sure why we're getting this error. If you're willing to debug, it would be much appreciated if you could pop a breakpoint on the culprit line (inside @purduesigbots/pros-cli-middleware/dist/util.js:110) to see what the data looks like. If not, we'll add a try/catch to at least print out the line to the console (but that won't really solve the issue)

>I'm not sure why we're getting this error. If you're willing to debug, it would be much appreciated if you could pop a breakpoint on the culprit line (inside @purduesigbots/pros-cli-middleware/dist/util.js:110) to see what the data looks like. If you'd like help walking through this, join [our Slack](https://pros-development.slack.com/) and we'll be glad to take you through the steps.

**Comment by mvas8037** [comment]
I don't have a slack account and it doesn't show a sign up page. Are you sure there isn't an easier way to resolve this issue?

**Comment by HotelCalifornia** [comment]
We haven't been able to reproduce this issue on our machines, so we don't know what's causing it. That is to say, it would be very enlightening if someone who is running into the issue could help us out debugging it.

You can join the slack workspace using [this link](https://join.slack.com/t/pros-development/shared_invite/enQtMzIyNzA2MTU2MDgwLWNlNTk3ZjA3ZWZmM2Q0YzI3NDZkZWE0MzU4ODdkM2U5MzhjZDY4M2RjNzBiZWYzODk0MTdkYzBiMzJjMWUyYmI) instead

**Comment by mvas8037** [comment]
What channel would I use to help to debug this error?

**Comment by brizuelasamuelito** [comment]
I got the same error but after that it said unable to start c++ server I don't know if that has somenthing to do with that or if that's just me

**Comment by mvas8037** [comment]
[JSON Error.mov.zip](https://github.com/purduesigbots/pros-atom3/files/3610417/JSON.Error.mov.zip)
Here's a video of the error.

**Comment by edjubuh** [comment]
Apologies for the delay in taking a look at this -- been in a cross country move and settling in to work.

Following up on the discussion in slack. I've opened purduesigbots/pros-cli-middleware#9 to help us debug these issue in the future. In the meantime so we can resolve your issue, will you modify that pros-cli-middleware/dist/util.js file that you put the breakpoint on to the following and let us know the results. With this information we should be able to see what string is causing the error.
```js
if (e.startsWith(PREFIX)) {
    try {
        var jdata = JSON.parse(e.substr(PREFIX.length));
        var primary = jdata.type.split('/')[0];
        _this.emit(primary, jdata);
    }
    catch (error) {
        console.error("Crashing while parsing \"" + e + "\"");
        throw error;
    }
}
else if (e.trim()) {
    console.log(e);
}
```

**Comment by mvas8037** [comment]
Where would the results be found? Is the code you posted an addition to the modification I made or is it what it should look like right now?

**Comment by Ali-Is-He** [comment]
sorry im not in the slack but am experiencing similar issues. Was this ever  resolved? Thank you!

**Comment by HotelCalifornia** [comment]
At this point I'm pretty sure that this error is non-fatal and can be safely ignored. We'll have to add the code to suppress the notification soon.

**Comment by thesaqibjavaid1** [comment]
please remove JSON.parse from your code. Enjoy

**Comment by HotelCalifornia** [comment]
> please remove JSON.parse from your code. Enjoy

hm. i'm not sure what this would accomplish exactly given that we need to parse the JSON data from the CLI in order to do anything with it, but thanks for the input

**Comment by itsdeepaklodhi** [comment]
i had the same error when i was conveying data from the server to my webpage, the reason for that is i was parsing JSON before the readyState was 4 .

```
<script type="text/javascript">
const Http = new XMLHttpRequest();
const url='xxxx';

Http.onreadystatechange = function(){

	 if (this.readyState == 4 && this.status == 200) {
	const b = JSON.parse(Http.responseText);
}		
}

Http.open("POST", url);
Http.send();

</script>
```
