### ISSUE TITLE
pros3: Build or Open terminal buttons not working

### ISSUE THREAD

**Issue by dnj12345** [purduesigbots/pros-atom3#41]
#### Expected Behavior:
When I press 'Build PROS Project', 'Open PROS Terminal' or the 'Quick PROS action' buttons, I expected something to happen i.e a terminal to pop-up, or a window opens up showing me code building etc

#### Actual Behavior:
Nothing happens. Its like my clicks aren't even registered. Only the 'Upload PROS Project' opens up an error window 'no cortext ports were found' which is true because I hadn't connected anything yet. However, I expected it to build the code.

#### Steps to reproduce:
This is a fresh install. I had an old PROS install which I used did two yrs ago. I removed everything and reinstalled everything using the instructions on this:

https://pros.cs.purdue.edu/v5/getting-started

Reinstalled atom and pros3-atom package. Created a new project and just added basic code from clawbot tutorial to test my system.

#### System information:
Operating System (e.g. Windows, OS X, Ubuntu): Windows 10

Atom Version: 1.40.1 x64

Plugin Version (PROS version): pros-atom3 1.1.0

#### Additional Information
Googling suggested that this could be related to windows security/firewall. However, the solution on how to resolve was not clear. I do have Window Security app running on my system. Is there some configuration or exclusion I need to add to get things working?

**Comment by HotelCalifornia** [comment]
Looking at the bug report, it seems that things like `make` were not installed correctly. Can you try running the installer again and selecting the "repair" option?

**Comment by dnj12345** [comment]
ok. Here's what I did.

- Uninstalled the pros-atom3 package from atom
- Installed pros again using the repair option like you suggested (did it twice).
- Started atom to see if pros-atom3 got automatically installed.
- It was not installed, neither did any of the PROS related buttons showed up.

- Uninstalled pros completely.
- Rebooted the system.
- Installed PROS again (64-bit). Although, I did select install programming cable driver which was not selected by default. I chose this option for all my previous installs.
- Again checked atom to see if the pros3 package was install. Still no luck.

Is there a log I can check to see what is preventing the proper installation?

**Comment by HotelCalifornia** [comment]
Are you able to run `prosv5 make` from command prompt (i.e. outside of the editor)?

**Comment by dnj12345** [comment]
As I mentioned in my second comment for this issue, it hangs the terminal with an error. Please see my previous message. It's give a python error and then hangs. The same issue pops in the inside editor terminal or outside one.

**Comment by HotelCalifornia** [comment]
> The same issue pops in the inside editor terminal or outside one.

Okay, this is what I wanted to know.

In any case, it looks like the installer isn't installing the toolchain for some reason. You mention that you added the cable driver component when running the installer, but I just want to confirm that you didn't deselect anything else, right?

**Comment by dnj12345** [comment]
No, I did not deselect anything. Are there any logs printed somewhere which will offer more clues? I'd really like to resolve this if possible. This used to work with old pros SW and cortex without any issues. Since upgrading nothing is working. 

BTW, is it necessary to have the vex connected for building? I didn't think it was for building.

**Comment by edjubuh** [comment]
Can you look at two things?
1. Check that PROS_TOOLCHAIN environment variable is correctly set. Press Windows key + R, then type `SystemPropertiesAdvanced`. On the window that opens up, click Environment Variables. In either the User Variables or System Variables section, you should see `PROS_TOOLCHAIN`.
2. That `C:\Program Files\PROS\toolchain` is a non-empty directory.

**Comment by dnj12345** [comment]
Both my user env. variables and system variables had the PROS_TOOLCHAIN env. variable and both of them were wrong. One was point to `C:\Program Files (x86)\PROS\toolchain` and the other was pointing to `C:\Program Files\PROS\toolchain\usr`. I changed them both to point to `C:\Program Files\PROS\toolchain`. 

Installed pros-atom3 package in atom (since none of the pros buttons were showing up) and restarted it. Still the same behavior. Pressing the build button or the open terminal button in atom doesn't do anything.

BTW, that directory (`C:\Program Files\PROS\toolchain`) is non-empty. Interesting, `dir` command shows only three directories tmp, usr and var. Where as an `ls` command shows seven directories bin, cygdrive, dev, proc, tmp, usr and var.

**Comment by edjubuh** [comment]
I'm guessing the user variable was pointing to the (x86) folder since those take precedence over system variables. PROS installer correctly set system variable but doesn't have any logic to detect if the user variable is set.

`PROS_TOOLCHAIN` should be `C:\Program Files\PROS\toolchain\usr`. If updating that still doesn't resolve issue, can you open developer console (`Ctrl` + `Shift` + `I`) and see if there are any errors in the console?

**Comment by dnj12345** [comment]
I don't see anything in the dev. console even after fixing the env. paths. Still nothing works :(

**Comment by HotelCalifornia** [comment]
> even after fixing the env. paths.

To clarify, did you make sure to close and reopen any command line windows and the editor after changing them?

**Comment by dnj12345** [comment]
yeah, I did do that.

**Comment by dnj12345** [comment]
Got a brand new computer. Mac this time. Installed atom and then installed pros3 as per the instructions here...

https://pros.cs.purdue.edu/v5/getting-started/macos.html

Based on what was mentioned earlier, following the instructions should have installed the atom packages. When I open Atom, I don't see PROS buttons. Do I have to install pros3-atom package by myself in Atom? These instructions seem to indicate that I don't have to if I follow 5 steps on the above-mentioned link...

**Comment by HotelCalifornia** [comment]
> When I open Atom, I don't see PROS buttons.

can you attach screenshots of what you do see? I think a better litmus test for whether the PROS package is installed is looking for the `PROS` menu in the menu bar, rather than for a toolbar (as the toolbar is provided by a separate plugin that may not have been installed properly).

the "PROS Editor" application is our fork of the Atom text editor, and the main differences are that we change the program name/icons, and that our package and its dependencies should be installed on first open. you examine the fork at https://github.com/purduesigbots/atom

the magic line is this one: https://github.com/purduesigbots/atom/commit/92c7a6f0b33926042ae3b844c7a51fbd070d77da#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R241

which includes the `pros-bootstrapper` package with the distributed application. this is why we continue to assert that, if everything has installed correctly, you do not need to install the pros-atom3 package manually.

**Comment by dnj12345** [comment]
uhm! Till you mentioned 'Pros Editor' application it didn't occur to me, I had to run the 'Pros Editor' app. Till now I was opening the regular Atom app and struggling with it. Either I missed it (at least its not mentioned in the documentation I've gone through) or this bit of info is not mentioned at all. The documentation directly jumps to c/c++ tutorial and then to ClawBot tutorial.

I'll go an check on my windows machine as well. It could be the same issue :(

**Comment by kunwarsahni01** [comment]
This seems resolved to me.
