### ISSUE TITLE
Can't find CLI in path

### ISSUE THREAD

**Issue by iamthehazard** [purduesigbots/pros-atom3#45]
**Describe the bug**
In the welcome screen, an error message appears (red box) saying "PROS CLI was not found in your PATH! Make sure PROS CLI is installed and available on PATH".

**To Reproduce**
For me, this occurs every time I run it, but for others it seems to be working fine.

**Expected behavior**
Expected no error message

**Screenshots**
How do I attach images

**Desktop (please complete the following information):**
Current PROS and Atom plugin version.
Running 10.15 macOS Catalina

**Additional context**
I can run `prosv5`in the terminal.

**Comment by iamthehazard** [comment]
A (most likely) related issue is that I can't obtain the kernels when creating a project. I can still click the create button, which results in #37

**Comment by kunwarsahni01** [comment]
Are you running the Atom Editor or the PROS Atom editor?

**Comment by iamthehazard** [comment]
I’m running atom with the pros package installed. I was told to ask this question here on another thread (you probably know, since you were the one who closed it)

**Comment by kunwarsahni01** [comment]
Yeah, you need to run the PROS editor, not the Atom Editor with the PROS Plugin, that is not currently a supported configuration.

**Comment by iamthehazard** [comment]
I see, thank you. It works now.
