### ISSUE TITLE
Installation Issue: 'cmd.exe' could not be spawned.

### ISSUE THREAD

**Issue by ann822** [purduesigbots/pros-atom3#46]
After installing the IDE, creating any default project.
When click the Quick Action button or the Build PROS Project button, the following warning will come out.

'cmd.exe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

But I do have this file and already set the environment settings correctly.
Does anyone meet this issue and fix it?

**Comment by kunwarsahni01** [comment]
This is a known issue with the latest release of the atom editor which was rolled back, try reinstalling the editor
